//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int productId { get; set; }
        public int ShopId { get; set; }
        public string Product_name { get; set; }
        public string Product_properties { get; set; }
    
        public virtual Shops Shops { get; set; }
    }
}
